### ISSUE TITLE
Required Keywords

### ISSUE THREAD

**Issue by RobertDober** [RobertDober/lab42_defkw#1]
It would be nice if required keywords could be specified too and an ArgumentError would be raised if at runtime the required keyword is not provided, e.g.

``` elixir
    defkw say_hello( to: :required, greeting: "Hello") do ...
```

and invocation  of `say_hello` w/o kwparam `to:...` will raise ArgumentError, however to use the atom `:required` somehow does not feel right as a default value `:required` will surely make sense very often.

**Comment by ericentin** [comment]
I had the same idea you had for this library last night and was thinking of implementing it! What a coincidence. Great work!

Perhaps, instead of using the atom `:required`, you could instead assign a [reference](http://elixir-lang.org/docs/stable/elixir/Kernel.html#make_ref/0) to a module attribute, and provide a function named something like `kw_required` to return that value. Then when you are looking for required parameters in invocations of `defkw`/`defkwp`, you can check whether the passed value equals the module attribute.

This has the dual purpose of allowing `:required` as a value and also would make it a little clearer that there is some "magic" afoot to someone that hasn't read the docs.

In code it would look like:

``` elixir
use Kwfuns

defkw do_thing(to: kw_required, greeting: "Hello") do
  ...
end
```

**Comment by RobertDober** [comment]
Thank you for your nice feedback. 
Using a reference is a great idea I will have a look how to expose a reference as `kw_required` in the modules using `Kwfuns`. I am not sure how to expose the module attribute. An idea would be to define a `kw_required` function in the module within `__using__`.

``` elixir
   @kw_required make_ref()
   defmacro __using__(_options) do
     quote do
        import unquote(__MODULE__)
        defp kw_required do: unquote(Module.get_attribute(__MODULE__, :kw_required))
     end
   end
```

Looks really nice. I do not think one can do something less invasive, or can one?

Thanx again.

**Comment by RobertDober** [comment]
Eventually I will go for an even simpler:

``` elixir
   def kw_required, do: fn -> end
   defmacro __using__(_options) do
     quote do
        import unquote(__MODULE__)
     end
   end
```

But you definitely put me onto the right track :+1:
